[package]
name = "biomimicry-genomes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Default genomes library for biomimicry engineering apps"
readme = "../../README.md"

[dependencies]
biomimicry = { workspace = true }

[lints]
workspace = true
